# Generated by Django 5.2.6 on 2026-06-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('tipo', models.CharField(choices=[('CIDADAO', 'Cidadão'), ('SERVIDOR', 'Servidor'), ('ADMIN', 'Administrador')], default='CIDADAO', max_length=20)),
            ],
        ),
    ]
